name: 🥕 Run Precios-Scraper

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Ejecutar Scraper
    runs-on: ubuntu-latest
    env:
      BASE_DIR: ${{ github.workspace }}
      OUT_DIR: ${{ github.workspace }}/out
      CREDS_JSON: creds.json
      SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
      WORKSHEET_NAME: precios_supermercados
      FILE_TAG: frutihort

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar credenciales de Google
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > creds.json

      - name: Ejecutar scraper.py
        run: python scraper.py

      - name: Publicar CSVs como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: precios-artefacto
          path: out/*.csv
