name: 🥕 Run Precios-Scraper
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: ${{ github.workspace }}
      OUT_DIR:  ${{ github.workspace }}/out
      FILE_TAG: frutihort
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Mostrar estructura del repo
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Añadir credenciales Google
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > creds.json

      - name: Ejecutar scraper
        run: |
          python tools/scraper/scraper.py     # ← ajusta la ruta

      - name: Publicar CSVs como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: precios-artefacto
          path: out/*.csv
